//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Directory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandatorSetting
    {
        public System.Guid UID { get; set; }
        public System.DateTime SysInsertTime { get; set; }
        public System.Guid SysInsertAccount { get; set; }
        public Nullable<System.DateTime> SysUpdateTime { get; set; }
        public Nullable<System.Guid> SysUpdateAccount { get; set; }
        public System.Guid MandatorUID { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual Mandator Mandator { get; set; }
    }
}
