//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Directory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mandator()
        {
            this.MandatorSetting = new HashSet<MandatorSetting>();
            this.User = new HashSet<User>();
        }
    
        public System.Guid UID { get; set; }
        public System.DateTime SysInsertTime { get; set; }
        public System.Guid SysInsertAccount { get; set; }
        public Nullable<System.DateTime> SysUpdateTime { get; set; }
        public Nullable<System.Guid> SysUpdateAccount { get; set; }
        public string Title { get; set; }
        public string EKEY { get; set; }
        public string IKEY { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public string LockedComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MandatorSetting> MandatorSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
