//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Directory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid UID { get; set; }
        public System.DateTime SysInsertTime { get; set; }
        public System.Guid SysInsertAccount { get; set; }
        public System.DateTime SysUpdateTime { get; set; }
        public System.Guid SysUpdateAccount { get; set; }
        public System.Guid UserUID { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public System.DateTime IntendedExpirationDate { get; set; }
        public Nullable<System.DateTime> ExpiratedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
