//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Directory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Session = new HashSet<Session>();
        }
    
        public System.Guid UID { get; set; }
        public System.DateTime SysInsertTime { get; set; }
        public System.Guid SysInsertAccount { get; set; }
        public Nullable<System.DateTime> SysUpdateTime { get; set; }
        public Nullable<System.Guid> SysUpdateAccount { get; set; }
        public System.Guid MandatorUID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public string LockedComment { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string CultureInfo { get; set; }
    
        public virtual Mandator Mandator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
